### ISSUE TITLE
Using winget as win32 app in User context (without admin permission)

### ISSUE THREAD

**Issue by arafelp** [o-l-a-v/winget-intune-win32#3]
I'm sorry, I just started using Intune + winget, I didn't fully understand how to deploy the application in the user context (without admin rights) such as GIMP.
The question is which script to use to create the .intunewin file, and if I understood correctly, in the Install field you need to use something like cmd /c ""%LOCALAPPDATA%\Microsoft\WindowsApps\winget.exe" install --exact --id GIMP. GIMP --silent --source winget --accept-package-agreements --accept-source-agreements"

**Comment by o-l-a-v** [comment]
For all examples in this repo using WinGet to install an application, the intunewin file is a dummy file with no content.

The install command for the Win32 calls WinGet directly, and not something inside the .intunewin file.

**Comment by arafelp** [comment]
and I didn't quite understand what the mention of this script is for?https://github.com/o-l-a-v/winget-intune-win32/blob/main/User%20context%20-%20Install/App%20-%20GIMP/WinGet%20-%20GIMP%20-%20Install%20parameters.md#script---app-installer--winget-minimum-version

**Comment by o-l-a-v** [comment]
A new enough version of WinGet must be present for the install command to work.

* <https://learn.microsoft.com/en-us/mem/intune/apps/apps-win32-add#step-3-requirements>

**Comment by arafelp** [comment]
simply, if I understand correctly, these actions assume that winget is already installed/updated on the computer?

**Comment by arafelp** [comment]
Please excuse me, but what is the way to pre-install\update winget on curnt user, using the Requirements from the link you provided?

**Comment by o-l-a-v** [comment]
> simply, if I understand correctly, these actions assume that winget is already installed/updated on the computer?

Yes.

> Please excuse me, but what is the way to pre-install\update winget on curnt user, using the Requirements from the link you provided?

I haven't solved that part yet. Microsoft Store will update apps eventually, and when App Installer ( <https://apps.microsoft.com/detail/9nblggh4nns1?hl=en-us&gl=us> ) eventuallly are updated, a recent enough version of WinGet will be present.

I started some work in progress stuff here to manually update App Installer and WinGet, but never went further than that:

* <https://github.com/o-l-a-v/winget-intune-win32/tree/main/Research/Requirements/WIP%20-%20App%20Installer%20minimum%20version>

**Comment by arafelp** [comment]
Understood, thank you very much for your work and for your answer

**Comment by o-l-a-v** [comment]
You're welcome. 😊 I'll close the issue. Feel free to comment if there is anything more.
